portfolio project  pull request
kirube1992/new-portfolio pull request #4
Opened 2023-03-24 20:35 UTC by kirube1992

portfolio project is add two parts about section and work section

2023-03-24 20:44 UTC, Shisui6 reviewed
Hi @kirube1992, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛠️

You have submitted a project, that does not have a professional readme. Please make sure to include all sections of the microverse readme [template](https://github.com/microverseinc/readme-template) and personalize them to your project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-24 21:15 UTC, souad988 reviewed
Hi @kirube1992 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a professional readme. Please make sure to include all sections of the microverse readme [template](https://github.com/microverseinc/readme-template) and personalize them to your project
as requested before your README has only the description and built with sections please make sure to add all missing sections from the template.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-24 22:03 UTC, Strangeal reviewed
Hi @kirube1992, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn’t have a professional `README` and pull request summary. As requested before by the previous reviewer personalize the README to the project needs. Please make sure to change your pull request title as well to reflect the work done in this feature branch: example: portfolio/setup mobile-first... 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-24 22:30 UTC, huseyinbiyik commented
Hi @kirube1992 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

- Kindly remove this broken link on your README.
<img width="656" alt="Screenshot 2023-03-25 at 1 25 26 AM" src="https://user-images.githubusercontent.com/25887253/227654485-b011407f-0ab7-4271-bb9e-63509e37c703.png">
- Since your project name is not Microverse README Template change here with your project name.
<img width="656" alt="Screenshot 2023-03-25 at 1 25 29 AM" src="https://user-images.githubusercontent.com/25887253/227654581-47bedc61-af5c-499e-8d71-4b365f4df9cd.png">
- Please remove this template text which is there for informing you not the visitor.
<img width="656" alt="Screenshot 2023-03-25 at 1 24 54 AM" src="https://user-images.githubusercontent.com/25887253/227654811-f68456b7-c0a5-4aa5-a66d-aec458d7456a.png">
- Please remove this unrelated link on the bottom of your README.
<img width="734" alt="Screenshot 2023-03-25 at 1 29 29 AM" src="https://user-images.githubusercontent.com/25887253/227654898-ace04bd7-467c-48f1-aadd-9cc6316e6f3f.png">


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-25 00:15 UTC, mahbubul14 requested changes
Hi @kirube1992,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

https://github.com/kirube1992/new-portfolio/blob/3f62701d79d620bdb55db5a28dff7258c58d138f/index.html#L13-L152

- [ ] It is better for your page to have just one h1 tag, this makes your website semantic and easily readable by browsers. Currently, you have multiple `h1` tags on your page. Kindly make it one. :+1: 

- [ ] Currently, you have used a ul for all elements. Kindly remove it as the ul tag is used to list items. :+1: 

- [ ] The main container of the projects has a display: grid. Please work on it :+1: 

- [ ] Your design is not matched the Figma design. Kindly work on it.

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![yourdesign_work](https://user-images.githubusercontent.com/70483835/227665664-7fe821fb-71d5-41b8-b4e5-053f0ff14dfb.png) | ![figma_work](https://user-images.githubusercontent.com/70483835/227665659-7e00732b-adcc-4dfc-9ba8-5dbce62f5328.png)

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![yourdesign_myself](https://user-images.githubusercontent.com/70483835/227665663-d509e40a-6ddc-4d55-b680-1c8dd05306df.png) | ![figma_myself](https://user-images.githubusercontent.com/70483835/227665657-4bff6fae-aa9c-40e6-82f2-515ecd78d53a.png)


https://github.com/kirube1992/new-portfolio/blob/3f62701d79d620bdb55db5a28dff7258c58d138f/index.html#L127-L150

- [ ] The technology categories ("Languages", "Frameworks" and "Skills") are in a ul, each of them in a li. :+1: 

- [ ] The technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list ul and each of them a li. :+1: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-25 08:09 UTC, kirube1992 commented
I correct all suggestion if anything else be more detail

2023-03-25 08:39 UTC, Strangeal requested changes
Hi @kirube1992 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Alt Text](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

 ## Required Changes ♻️
- [ ] Please make sure your work section looks exactly like the FIgma template in terms of (margin, padding, border, button hover effect, and color) because what you have currently doesn't look the same. 

Your design:
<img width="373" alt="Screenshot 2023-03-25 at 01 28 48" src="https://user-images.githubusercontent.com/107192076/227706776-351fd758-809a-4270-ad1f-edeaa1837674.png">


Figma Design: 
<img width="332" alt="Screenshot 2023-03-25 at 01 32 17" src="https://user-images.githubusercontent.com/107192076/227706800-d10f96f7-4c60-4bff-96ef-217e750745f6.png">

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 10:29 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @kirube1992, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 10:29 UTC, Qoosim commented on index.html
>      <ul>
- [ ] As mentioned by the previous reviewer, the margin between the headline and your works section is not as we have it on the Figma design. Kindly look into it and fix.

### Your Design
![your-header-projects](https://user-images.githubusercontent.com/26597432/227710533-0b16c487-4c2b-45b4-8b8b-f402def5a100.png)

### Figma Design
![temp-header-project](https://user-images.githubusercontent.com/26597432/227710546-8c4fb70b-8f98-44cd-a5bf-81dc84aa6b8e.png)

2023-03-25 10:29 UTC, Qoosim commented on index.html
> +            <img class="abfr1" src="./images/download.png" alt="arrow icon">
- [ ] Great job implmenting the changes from previous reviewer. However, there is one small thing you need to work on. The direction of the arrow on the language and the framework and skill are not align with what we have on the Figma design. Kindly look at them and fix.

### Your Design
![your-lang](https://user-images.githubusercontent.com/26597432/227711260-e60d461a-9cc6-4d9f-bc27-d70442cb56e8.png)

### Figma Design
![temp-lang](https://user-images.githubusercontent.com/26597432/227711248-fe201888-4152-4b04-8d86-8f3594ff64f9.png)

2023-03-25 10:29 UTC, Qoosim commented on index.html
> +    </ul>
- [ ] As suggested by the previous reviewer, I would like to recommend you to give a closer look into the figma design and make your design look almost exactly. This includes, color, font-size, font-weight, font-style, margin, padding background-color among others. I would love to encourage your to work your design alongsize the figma design element by element.

### Your Design
![your-works](https://user-images.githubusercontent.com/26597432/227711654-e680cd5d-ec81-414e-b893-1af3d487756c.png)

### figma Design
![temp-works](https://user-images.githubusercontent.com/26597432/227711663-cfbe3051-e449-4591-a0ef-ae2a138e6483.png)

2023-03-25 13:19 UTC, NahnahAJ approved these changes
## Project Status: APPROVED :green_circle: 
Hi @kirube1992, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
- All requested changes completed :heavy_check_mark: 

## Optional suggestions
- I will suggest that you improve upon the mobile view of your project. Even though you fixed all the changes requested, you can see that your project is still missing some aspects of the original FIgma design. So I will suggest that in your free time, you try to work on that so your project looks exactly like the Figma Design :+1: 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 17:59 UTC, merged