Desktop-version-pull-request
kirube1992/new-portfolio pull request #6
Opened 2023-03-31 21:45 UTC by kirube1992

2023-03-31 23:39 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @kirube1992 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 23:39 UTC, abdulhamiid commented on index.html
> +      <div class="last">
Figma
![image](https://user-images.githubusercontent.com/78251927/229242682-0708fd9d-a8b5-452a-b511-cad6e972bf11.png)

Your design
![image](https://user-images.githubusercontent.com/78251927/229242628-8bd11790-f58a-4f79-b6e5-815072387620.png)

- [ ] According to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md), we should replicate the design as much as possible.

- [ ] Let's consider using the same background image as Figma in this section so that our design looks similar to the template 👍

- [ ] Also, kindly increase the `font-size` of the text in this section to match the template.

2023-03-31 23:39 UTC, abdulhamiid commented on style.css
> +  }
After implementing the desktop design, kindly check also that the mobile design still looks as expected. 🤗

Your design (This section is affected by the desktop stylings) please let's make adjustments. 
![image](https://user-images.githubusercontent.com/78251927/229244256-90939f97-80ff-4dcc-9cbb-c343dceb1007.png)

Figma
![image](https://user-images.githubusercontent.com/78251927/229244730-1828d9d0-2ed9-4330-ae53-78461d50d76f.png)

2023-03-31 23:39 UTC, abdulhamiid commented on index.html
> +        <p class="oldo">Facebook 360</p>
Your design at screen size (863px)
![image](https://user-images.githubusercontent.com/78251927/229249349-5526ea0a-484a-43e4-a0f2-7b5e69c24bc7.png)

- [ ] I notice that the page is not responsive and I can see a horizontal scroll bar when I resize the screen🤔

- [ ] Please let's fix the issues with the page responsiveness, It is important that our design remains responsive in the desktop version(768px or higher).

- [ ] Kindly use media queries in your CSS file to make your desktop version look like the template you selected (Desktop: >=768px).

2023-04-01 12:15 UTC, bienvenuushindi approved these changes
# STATUS: APPROVED 🟢 

## Hi @kirube1992   👋, 

Well done implementing the requested changes 👏
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/lJNoBCvQYp7nq/giphy.gif"/>

### Highlights 🎯 
:+1: No linter errors✔️
:+1: Good PR title

### Optional Suggestions

**_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 12:15 UTC, bienvenuushindi commented on index.html
>              feature or website Look through some of my work and experience!
:orange_circle: [OPTIONAL] Kindly make sure you indent your logo properly on your mobile version to match the Figma Design. Please consider adding more room around  the page  content  to reflect closely the Figma Design

Your Design
![indentation](https://user-images.githubusercontent.com/26736582/229287421-81e00f04-d8a7-48bb-bc29-53f33d4da4da.png)


Figma Design

![figmaspacing](https://user-images.githubusercontent.com/26736582/229287427-ef764bbd-eaaf-48f0-b04a-88ffd32ee9c4.png)

2023-04-01 12:15 UTC, bienvenuushindi commented on index.html
>        </div>
:orange_circle: [OPTIONAL] Please make sure you use the proper background color on  each list item to match the Figma Design

Your Design
![properbackgroundstudent](https://user-images.githubusercontent.com/26736582/229287649-75674e1d-2ea3-4285-b1d7-8400fa9d9015.png)

Figma Design
![properbackground](https://user-images.githubusercontent.com/26736582/229287655-1eb773fe-f80d-46cb-8e64-5faa6e7edfe9.png)

2023-04-01 12:15 UTC, bienvenuushindi commented on index.html
>              <p>JavaScript</p>
:orange_circle: [OPTIONAL] Please make sure the bottom borders are applied to each item to match the Figma Design. 
Your Design
![missing border](https://user-images.githubusercontent.com/26736582/229287926-38c47142-6b10-4e5a-a500-9e1fb62994db.png)
Figma Design
![figmaborder](https://user-images.githubusercontent.com/26736582/229287938-14aa52e4-6377-40ef-973b-ba67e139d242.png)

Also, Note that for semantics reasons you should use
```
 <ul>
<li>Languages.
     <ul>
         <li>Javascript</li>
        <li>CSS</li>
       <li>HTML</li>
   </ul>
</li>
<li>Frameworks</li>
<li>Skills</li>
</ul>
```

2023-04-01 12:30 UTC, merged